### ISSUE TITLE
Feature: Display Key metrics

### ISSUE THREAD

**Issue by gsytnik** [Bob-Loth/csc-307#11]

**Comment by Bob-Loth** [comment]
Dashboard contains 2 views: View Products Near Expiry, and View Low Stock Items. These are condensed views of specific filterable criteria. 
Clicking on these views will redirect to (not decided yet: either the search-filter page with the filter pre-set, or a new page with that same filter used).

**Comment by Bob-Loth** [comment]
Too similar in scope to Generic List View, merged time estimates with that issue.
