### ISSUE TITLE
Feature: View and Edit a Specific Product or Shipment

### ISSUE THREAD

**Issue by david-1-nguyen** [Bob-Loth/csc-307#12]

**Comment by Bob-Loth** [comment]
- [ x] Add Modal component to SearchFilter Table that displays current info for product
- [ ] Add Form.Input component to Modal that shows current info, and gives input box to change info
- [ ] Pressing "Save Changes" button updates that particular item. (_id should be the same, but one or more data fields should change)

**Comment by Bob-Loth** [comment]
I've got an editFormatting function added that will check any potential submission for formatting errors. Next step for me is adding the Form component in.

**Comment by Bob-Loth** [comment]
Added the form component. It sends a patch request with the information it is requesting to update. Not currently handled by backend just yet.

**Comment by Bob-Loth** [comment]
Sends patch request. Patch request is received, and performs a find_one_and_update on the document identified by _id in the url argument, and according to the patch object sent in the request body.
